/**
 * Selectable driver cities. Values mirror the `GeorgianCity` Prisma enum; they
 * are duplicated here (rather than imported from `@prisma/client`) to keep the
 * server-only Prisma client out of the browser bundle. `region` is used by the
 * onboarding wizard's searchable city dropdown ("Batumi · Adjara") — existing
 * callers that only read `value`/`label` (the sign-up form, the company
 * dashboard's add-driver drawer) are unaffected by its addition.
 */
export const GEORGIAN_CITY_OPTIONS = [
  { value: "TBILISI", label: "Tbilisi", region: "Tbilisi" },
  { value: "BATUMI", label: "Batumi", region: "Adjara" },
  { value: "KUTAISI", label: "Kutaisi", region: "Imereti" },
  { value: "RUSTAVI", label: "Rustavi", region: "Kvemo Kartli" },
  { value: "ZUGDIDI", label: "Zugdidi", region: "Samegrelo" },
  { value: "GORI", label: "Gori", region: "Shida Kartli" },
  { value: "POTI", label: "Poti", region: "Samegrelo" },
  { value: "SAMTREDIA", label: "Samtredia", region: "Imereti" },
  { value: "KHASHURI", label: "Khashuri", region: "Shida Kartli" },
  { value: "SENAKI", label: "Senaki", region: "Samegrelo" },
  { value: "ZESTAPONI", label: "Zestaponi", region: "Imereti" },
  { value: "MARNEULI", label: "Marneuli", region: "Kvemo Kartli" },
  { value: "TELAVI", label: "Telavi", region: "Kakheti" },
  { value: "AKHALTSIKHE", label: "Akhaltsikhe", region: "Samtskhe-Javakheti" },
  { value: "OZURGETI", label: "Ozurgeti", region: "Guria" },
  { value: "KOBULETI", label: "Kobuleti", region: "Adjara" },
  { value: "CHIATURA", label: "Chiatura", region: "Imereti" },
  { value: "TSKALTUBO", label: "Tskaltubo", region: "Imereti" },
  { value: "SAGAREJO", label: "Sagarejo", region: "Kakheti" },
  { value: "GARDABANI", label: "Gardabani", region: "Kvemo Kartli" },
  { value: "BOLNISI", label: "Bolnisi", region: "Kvemo Kartli" },
  { value: "AKHALKALAKI", label: "Akhalkalaki", region: "Samtskhe-Javakheti" },
  { value: "BORJOMI", label: "Borjomi", region: "Samtskhe-Javakheti" },
  { value: "KASPI", label: "Kaspi", region: "Shida Kartli" },
  { value: "MTSKHETA", label: "Mtskheta", region: "Mtskheta-Mtianeti" },
  { value: "TKIBULI", label: "Tkibuli", region: "Imereti" },
  { value: "KARELI", label: "Kareli", region: "Shida Kartli" },
  { value: "GURJAANI", label: "Gurjaani", region: "Kakheti" },
  { value: "KVARELI", label: "Kvareli", region: "Kakheti" },
  { value: "LANCHKHUTI", label: "Lanchkhuti", region: "Guria" },
  { value: "SACHKHERE", label: "Sachkhere", region: "Imereti" },
  { value: "TERJOLA", label: "Terjola", region: "Imereti" },
  { value: "KHOBI", label: "Khobi", region: "Samegrelo" },
  { value: "MARTVILI", label: "Martvili", region: "Samegrelo" },
  { value: "TSALENJIKHA", label: "Tsalenjikha", region: "Samegrelo" },
  { value: "ABASHA", label: "Abasha", region: "Samegrelo" },
  { value: "AMBROLAURI", label: "Ambrolauri", region: "Racha-Lechkhumi" },
  { value: "TSAGERI", label: "Tsageri", region: "Racha-Lechkhumi" },
  { value: "ONI", label: "Oni", region: "Racha-Lechkhumi" },
  { value: "MESTIA", label: "Mestia", region: "Svaneti" },
  { value: "SIGHNAGHI", label: "Sighnaghi", region: "Kakheti" },
  { value: "DEDOPLISTSQARO", label: "Dedoplistsqaro", region: "Kakheti" },
  { value: "LAGODEKHI", label: "Lagodekhi", region: "Kakheti" },
  { value: "AKHMETA", label: "Akhmeta", region: "Kakheti" },
  { value: "DUSHETI", label: "Dusheti", region: "Mtskheta-Mtianeti" },
  { value: "TIANETI", label: "Tianeti", region: "Mtskheta-Mtianeti" },
  { value: "TSALKA", label: "Tsalka", region: "Kvemo Kartli" },
  { value: "DMANISI", label: "Dmanisi", region: "Kvemo Kartli" },
  { value: "TETRITSQARO", label: "Tetritsqaro", region: "Kvemo Kartli" },
  { value: "NINOTSMINDA", label: "Ninotsminda", region: "Samtskhe-Javakheti" },
  { value: "ADIGENI", label: "Adigeni", region: "Samtskhe-Javakheti" },
  { value: "ASPINDZA", label: "Aspindza", region: "Samtskhe-Javakheti" },
  { value: "VALE", label: "Vale", region: "Samtskhe-Javakheti" },
  { value: "BAGHDATI", label: "Baghdati", region: "Imereti" },
  { value: "VANI", label: "Vani", region: "Imereti" },
  { value: "KHARAGAULI", label: "Kharagauli", region: "Imereti" },
  { value: "KHONI", label: "Khoni", region: "Imereti" },
  { value: "CHKHOROTSQU", label: "Chkhorotsqu", region: "Samegrelo" },
  { value: "JVARI", label: "Jvari", region: "Samegrelo" },
  { value: "KEDA", label: "Keda", region: "Adjara" },
  { value: "KHELVACHAURI", label: "Khelvachauri", region: "Adjara" },
  { value: "KHULO", label: "Khulo", region: "Adjara" },
  { value: "SHUAKHEVI", label: "Shuakhevi", region: "Adjara" },
] as const;
